### ISSUE TITLE
Prefix string too short exception when getting "data://"

### ISSUE THREAD

**Issue by zeynepsu** [algorithmiaio/algorithmia-java#4]
Better error message needed for:

``` java
File file = Algorithmia.file(imageUrl).getFile();
```

throws:

``` java
Error: java.lang.IllegalArgumentException: Prefix string too short
java.lang.IllegalArgumentException: Prefix string too short
    at java.io.File.createTempFile(File.java:2001)
    at java.io.File.createTempFile(File.java:2070)
    at com.algorithmia.data.DataFile.getFile(DataFile.java:47)
    at algorithmia.sfw.NudityDetectionHelper.ObjectDetectionWithModels.apply(ObjectDetectionWithModels.java:39)
    at algorithmia.sfw.NudityDetectionHelper.NudityDetectionHelper.apply(NudityDetectionHelper.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at algorithmia.runners.JavaRunner$.applyInput(JavaRunner.scala:234)
    at algorithmia.runners.JavaRunner$.algorithmia$runners$JavaRunner$$tryNativeApply(JavaRunner.scala:185)
    at algorithmia.runners.JavaRunner$$anonfun$applyString$1.apply(JavaRunner.scala:30)
    at algorithmia.runners.JavaRunner$$anonfun$applyString$1.apply(JavaRunner.scala:27)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at algorithmia.runners.JavaRunner$.applyString(JavaRunner.scala:27)
    at algorithmia.runners.JarRunner.run(JarRunner.scala:52)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply$mcV$sp(AlgoRunner.scala:27)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply(AlgoRunner.scala:23)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply(AlgoRunner.scala:23)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by zeynepsu** [comment]
This also happens when I send "data://.me/"

**Comment by zeynepsu** [comment]
And when I send it in with existent or non existent collections.

**Comment by anowell** [comment]
interesting... Ultimately, you can't use `.file(..).getFile()` on a directory/collection, since it needs to know what filename to use. But, we could certainly check that getName returned a string with length > 0 before trying to create a temporary file, and cleanup the error message accordingly:

Relevant code:

``` java
File tempFile = File.createTempFile(getName(), null);
```

Looking at getName():

``` java
public String getName() {
    return this.path.substring(this.path.lastIndexOf("/") + 1);
}
```

**Comment by Argoday** [comment]
Why is a temp file needed at all here?

**Comment by anowell** [comment]
`getFile()` doesn't take a "where do you want to store this file" argument. It returns a File and the caller can use it however they want (including moving it out of temp).

**Comment by Argoday** [comment]
1) Why is it creating the file before the network request? (strange ordering of events)
2) Why parse into the data uri? ... just create a temp file using a uuid based filename

**Comment by anowell** [comment]
1) Seems like a generally good idea to initialize local resource before making the network request, e.g., if it had been trying to create a file at a specific location that results in permission denied, then performing the request first would result in a wasted download. There are similar fail conditions for creating a temp file, so I still think this makes sense.

2) temp files are created with a prefix string that is taken to generate a unique filename, which makes a uuid a bit overkill. Since in valid uses of `getFile` I had a filename at my disposal, it seemed like a natural choice, but a closer read of the `createTempFile` docs recommends picking short prefixes and that the prefix must be at least 3 chars. So I now believe there is actually a bigger bug here: **you can't download files with 1 or 2 character filenames.** I'm gonna make a change to just use "algodata" as the prefix, and this whole problem should go away (and zeynep's particular scenario will result in an error message that comes from the API).
