### ISSUE TITLE
Missing URL encoding of data_uri

### ISSUE THREAD

**Issue by Argoday** [algorithmiaio/algorithmia-java#5]
This line fails:
Algorithmia.client().file("data://.my/This is a valid filename ☘.txt").put("hi");

The client should perform a URLEncode operation prior to sending HTTP requests for data_uris

**Comment by Argoday** [comment]
## Stacktrace:

Error: java.lang.IllegalArgumentException: Illegal character in path at index 43: http://172.17.42.1:4160/v1/data/.my/he/test file ☘.txt
java.lang.IllegalArgumentException: Illegal character in path at index 43: http://172.17.42.1:4160/v1/data/.my/he/test file ☘.txt (Illegal character in path at index 43: http://172.17.42.1:4160/v1/data/.my/he/test file ☘.txt)
    at java.net.URI.create(URI.java:852)
    at org.apache.http.client.methods.HttpPut.<init>(HttpPut.java:68)
    at com.algorithmia.client.HttpClient.put(HttpClient.java:90)
    at com.algorithmia.data.DataFile.put(DataFile.java:91)
    at algorithmia.AwesomeJava2.AwesomeJava2.apply(AwesomeJava2.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at algorithmia.runners.JavaRunner$.applyInput(JavaRunner.scala:234)
    at algorithmia.runners.JavaRunner$.algorithmia$runners$JavaRunner$$tryFullBodyApply(JavaRunner.scala:229)
    at algorithmia.runners.JavaRunner$$anonfun$applyString$3.apply(JavaRunner.scala:56)
    at algorithmia.runners.JavaRunner$$anonfun$applyString$3.apply(JavaRunner.scala:53)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at algorithmia.runners.JavaRunner$.applyString(JavaRunner.scala:53)
    at algorithmia.runners.JarRunner.run(JarRunner.scala:53)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply$mcV$sp(AlgoRunner.scala:27)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply(AlgoRunner.scala:23)
    at algorithmia.runners.AlgoRunner$$anonfun$invoke$1.apply(AlgoRunner.scala:23)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: Illegal character in path at index 43: http://172.17.42.1:4160/v1/data/.my/he/test file ☘.txt
